<?php

namespace KoolDevelop;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-13 at 11:03:27.
 */
class StringUtilitiesTest extends \PHPUnit_Framework_TestCase {

    /**
     * Simple Test case for StringUtilities::underscore
     * 
     * @covers KoolDevelop\StringUtilities::underscore
     */
    public function testUnderscoreBasic() {
        $this->assertEquals('test_string', StringUtilities::underscore('TestString'));
    }
    
    /**
     * Simple Test case for StringUtilities::underscore
     * 
     * @covers KoolDevelop\StringUtilities::underscore
     */
    public function testUnderscoreDoubleCaps() {
        $this->assertEquals('test_s_string', StringUtilities::underscore('TestSString'));
    }


    /**
     * Simple Test case for StringUtilities::camelcase
     * 
     * @covers KoolDevelop\StringUtilities::camelcase
     */
    public function testCamelcaseBasic() {
        $this->assertEquals('TestString', StringUtilities::camelcase('test_string'));
    }
    
    /**
     * Simple Test case for StringUtilities::camelcase
     * 
     * @covers KoolDevelop\StringUtilities::camelcase
     */
    public function testCamelcaseDoubleUnderscore() {
        $this->assertEquals('Test_string', StringUtilities::camelcase('test__string'));
    }

    /**
     * Simple Test case for StringUtilities::ascii
     * 
     * @covers KoolDevelop\StringUtilities::ascii
     */
    public function testAsciiBasic() {
        $this->assertEquals('aaaa eeee iiii ooooo', StringUtilities::ascii('âäáà êèéë îïìí ôöõòó'));
    }

}
