<?php

namespace KoolDevelop\Route;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-13 at 11:26:03.
 */
class LiteralTest extends \PHPUnit_Framework_TestCase {
    
    /**
     * Test Literal Routing
     * 
     * @covers KoolDevelop\Route\Literal::route()
     */
    public function testLiteralRoute() {
        $wildcard = new Literal('/testcase/', '/success/');
        $route = '/testcase/';
        $wildcard->route($route);
        $this->assertEquals('/success/', $route);
    }

    
}
