<?php

namespace KoolDevelop\Route;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-13 at 11:26:03.
 */
class RegExTest extends \PHPUnit_Framework_TestCase {
    
    /**
     * Test Basic RegEx Routeing
     * 
     * @covers KoolDevelop\Route\RegEx::route()
     */
    public function testRegExBasic() {
        $wildcard = new RegEx('/\/test(a|b|c|d|e)?ase\//', '/success/');
        $route = '/testcase/';
        $wildcard->route($route);
        $this->assertEquals('/success/', $route);
    }

    /**
     * Test Basic RegEx Routeing
     * 
     * @covers KoolDevelop\Route\RegEx::route()
     */
    public function testRegExWithReplacements() {
        $wildcard = new RegEx('/\/test(case)\//', '/success/$1');
        $route = '/testcase/';
        $wildcard->route($route);
        $this->assertEquals('/success/case', $route);
    }
}
